name: pre-commit

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Get changed files
      uses: tj-actions/changed-files@v44
      id: changed-files

    - name: List changed files
      run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
    
    - name: Local pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
    